### ISSUE TITLE
Application throwing Object [object Object] has no method 'type' 

### ISSUE THREAD

**Issue by jsbranco** [meteor/galaxy-seo-package#1]
Hi,

After adding the mdg:seo package, my application randomly throws the below error ( I believe its whenever the cralwer is hitting the site) 

This seem to be an issue with the package dfisher:prerenderio, related to this : https://github.com/dfischer/meteor-prerenderio/issues/7

I am tempted to use dferber90's package as it seems to resolve the error thown problem for this particular case. I was wondering if a PR for mdg:seo should be in place to update the package from dfisher to dferber90?

```
2016-02-13 20:36:23+08:00TypeError: Object [object Object] has no method 'type'
8qzw
2016-02-13 20:36:23+08:00 at ServerResponse.send (packages/dfischer_prerenderio/dfischer_prerenderio.js:97:1)
8qzw
2016-02-13 20:36:23+08:00 at /app/bundle/programs/server/npm/dfischer_prerenderio/node_modules/prerender-node/index.js:20:20
8qzw
2016-02-13 20:36:23+08:00 at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/dfischer_prerenderio/node_modules/prerender-node/index.js:191:5)
8qzw
2016-02-13 20:36:23+08:00 at IncomingMessage.emit (events.js:117:20)
8qzw
2016-02-13 20:36:23+08:00 at _stream_readable.js:944:16
8qzw
2016-02-13 20:36:23+08:00 at process._tickDomainCallback (node.js:492:13)
8fvm
2016-02-13 20:50:23+08:00TypeError: Object [object Object] has no method 'type'
8fvm
2016-02-13 20:50:23+08:00 at ServerResponse.send (packages/dfischer_prerenderio/dfischer_prerenderio.js:97:1)
8fvm
2016-02-13 20:50:23+08:00 at /app/bundle/programs/server/npm/dfischer_prerenderio/node_modules/prerender-node/index.js:20:20
8fvm
2016-02-13 20:50:23+08:00 at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/dfischer_prerenderio/node_modules/prerender-node/index.js:191:5)
8fvm
2016-02-13 20:50:23+08:00 at IncomingMessage.emit (events.js:117:20)
8fvm
2016-02-13 20:50:23+08:00 at _stream_readable.js:944:16
8fvm
2016-02-13 20:50:23+08:00 at process._tickDomainCallback (node.js:492:13)
rzdy
2016-02-13 20:58:51+08:00TypeError: Object [object Object] has no method 'type'
rzdy
2016-02-13 20:58:51+08:00 at ServerResponse.send (packages/dfischer_prerenderio/dfischer_prerenderio.js:97:1)
rzdy
2016-02-13 20:58:51+08:00 at /app/bundle/programs/server/npm/dfischer_prerenderio/node_modules/prerender-node/index.js:20:20
rzdy
2016-02-13 20:58:51+08:00 at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/dfischer_prerenderio/node_modules/prerender-node/index.js:191:5)
rzdy
2016-02-13 20:58:51+08:00 at IncomingMessage.emit (events.js:117:20)
rzdy
2016-02-13 20:58:51+08:00 at _stream_readable.js:944:16
rzdy
2016-02-13 20:58:51+08:00 at process._tickDomainCallback (node.js:492:13)
18zp
2016-02-13 21:15:00+08:00TypeError: Object [object Object] has no method 'type'
18zp
2016-02-13 21:15:00+08:00 at ServerResponse.send (packages/dfischer_prerenderio/dfischer_prerenderio.js:97:1)
18zp
2016-02-13 21:15:00+08:00 at /app/bundle/programs/server/npm/dfischer_prerenderio/node_modules/prerender-node/index.js:20:20
18zp
2016-02-13 21:15:00+08:00 at IncomingMessage.<anonymous> (/app/bundle/programs/server/npm/dfischer_prerenderio/node_modules/prerender-node/index.js:191:5)
18zp
2016-02-13 21:15:00+08:00 at IncomingMessage.emit (events.js:117:20)
18zp
2016-02-13 21:15:00+08:00 at _stream_readable.js:944:16
18zp
2016-02-13 21:15:00+08:00 at process._tickDomainCallback (node.js:492:13)
```

**Comment by artahian** [comment]
+1

**Comment by BudickDa** [comment]
+1

I have a blank page and
`res.send(status, body): Use res.status(status).send(body) instead`
in the console. 

Exactly like in the referenced issue.

**Comment by artahian** [comment]
I started using this instead: https://github.com/dferber90/meteor-prerender
seems to work fine so far.

**Comment by filipenevola** [comment]
I don't think this issue is happening in current versions.
